name: Docker Image CI

on:
  push:
    branches:
      - 'main'
  schedule:
    - cron:  '30 20 * * *'

jobs:
  mtf-rip:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: mtf.rip
          push: true
          cache-from: type=registry,ref=vxst/mtf.rip:latest
          cache-to: type=inline
          tags: vxst/mtf.rip:latest, vxst/mtf.rip:${{ steps.date.outputs.date }}
      -
        name: Deployment
        uses: vxst/eks-kubectl-action@v2.0
        with:
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-1
          cluster_name: matrix
          args: rollout restart deployment mtf-rip -n sites
  oiwiki:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      - 
        name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Clone OIWiki
        run: git clone https://github.com/OI-wiki/OI-wiki.git -b gh-pages oiwiki/html --depth 1 && rm -rf oiwiki/html/.git
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: oiwiki
          push: true
          cache-from: type=registry,ref=vxst/oiwiki:latest
          cache-to: type=inline
          tags: vxst/oiwiki:latest, vxst/oiwiki:${{ steps.date.outputs.date }}
      -
        name: Deployment
        uses: vxst/eks-kubectl-action@v2.0
        with:
          aws_access_key_id:  ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_region: ap-northeast-1
          cluster_name: matrix
          args: rollout restart deployment oiwiki-vx-st -n sites
